### ISSUE TITLE
extension NonEmpty where C: MutableCollection, C.Index == Int isn't safe

### ISSUE THREAD

**Issue by ole** [pointfreeco/swift-nonempty#1]
Your [`extension NonEmpty where C: MutableCollection, C.Index == Int`](https://github.com/pointfreeco/swift-nonempty/blob/11467e7851e17b4ae64a15a59c7b23041c1373e1/Sources/NonEmpty/NonEmpty%2BMutableCollection.swift#L22-L31) breaks for base collections that have integer indices that don't necessarily start at zero, such as `ArraySlice` or `Data`.

Example: this test crashes with "Fatal error: Index out of bounds".

```swift
  func testMutableCollectionWithArraySlice() {
    let numbers = Array(1...10)
    var xs = NonEmpty(0, numbers[5...])
    xs[1] = 43
    XCTAssertEqual(43, xs[1])
  }
```

**Comment by mbrandonw** [comment]
lol you're fast, we haven't even announced this yet! 🤫

**Comment by ole** [comment]
Lol, sorry. 😜 I didn't even notice this was brand new. I watched [your last episode](https://www.pointfree.co/episodes/ep19-algebraic-data-types-generics-and-recursion) yesterday and heard you talk about non-empty collections and that inspired me to start writing this myself. When I got stuck it occurred to me I should look whether you guys had written a similar type and that's when I found this.
