### ISSUE TITLE
Duplicated keys in NonEmpty dictionary

### ISSUE THREAD

**Issue by onmyway133** [pointfreeco/swift-nonempty#12]
Hi, thanks for this great library. I was just curious how you handle some conflicts for specific collections, as each collection has certain characteristics. For example, dictionary can't store duplicated keys

```swift
let zs = NonEmpty<[Int: String]>((1, "one"), [1: "one again", 3: "three"])
```

I think we need to have specific init extension for each kind of collection, like for `Set` 🤔 

```swift
extension NonEmpty where C: SetAlgebra
```

**Comment by stephencelis** [comment]
Hi! That line of code already traps, just like in the standard library:

``` swift
NonEmpty<[Int: String]>((1, "one"), [1: "one again", 3: "three"])
// 🛑 Fatal error: Dictionary contains duplicate key

[1: "one", 1: "one again", 3: "three"]
// 🛑 Fatal error: Dictionary literal contains duplicate keys
```

**Comment by onmyway133** [comment]
@stephencelis didn't know that, thanks 💪
