### ISSUE TITLE
Unexpected behaviour in MutableCollection's subscript 

### ISSUE THREAD

**Issue by DmT021** [pointfreeco/swift-nonempty#17]
In the issue https://github.com/pointfreeco/swift-nonempty/issues/1 you fixed the case:
```
  func testMutableCollectionWithArraySlice() {
    let numbers = Array(1...10)
    var xs = NonEmpty(0, numbers[5...])
    xs[1] = 43
    XCTAssertEqual(43, xs[1])
  }
```
But is it expected to have an index `1` on a NonEmpty of ArraySlice starting with 5?

**Comment by stephencelis** [comment]
We ended up revising this, and the behavior is now index 6, as expected with the merging of #26 (we just forgot to close this out). Thanks for the report!
