### ISSUE TITLE
Internal Codable conformances prevent custom implementations

### ISSUE THREAD

**Issue by jakeatoms** [pointfreeco/swift-nonempty#21]
I was attempting to decode a network response that contains an array directly to `NonEmpty`. However, the synthesized decodable `init` does not work with an array as the input. I attempted to override the synthesized `init` via an extension, but it's ignored at runtime.

I'm wondering if we could remove that conformance from the library and let clients add the conformance as needed to allow for more flexible decoding. The other option is that I'm doing something wrong, of course :)

**Comment by stephencelis** [comment]
I think this is addressed in `master`.
