### ISSUE TITLE
Convert to array

### ISSUE THREAD

**Issue by phlippieb** [pointfreeco/swift-nonempty#24]
Hi 👋 

I'm trying this library out in my codebase. I already have a naive extension on Array -- a computed property called `nonEmpty` -- which returns self if the array has at least one element, or nil otherwise. Literally just

```
extension Array {
    var nonEmpty: Array<Element>? {
        guard !self.isEmpty else { return nil }
        return self
    }
}
```

But I would rather use the `NonEmptyArray` type in this library. So I changed my extension to return a `NonEmptyArray` if possible, like this:

```
import NonEmpty

extension Array {
    var nonEmpty: NonEmptyArray<Element>? {
        guard let head = self.first else { return nil }
        let tail = Array(self.dropFirst())
        return NonEmptyArray(head, tail)
    }
}
```

Now the problem is that all my existing code that depends on this extension still expects the result to be an Array, and not a NonEmptyArray. The two are of course not interchangeable.

Logically, if you think about it, a NonEmptyArray is functionally equivalent to an Array (though not the other way around). Any operation or method that takes a list of something should also work with a non-empty list of those things. So I was wondering if you have any tips for elegantly converting from NonEmptyArray to Array? Best I've come up with so far is a computed property on NonEmptyArray, or an initialiser on Array. Swift is (for better or for worse) deliberately designed to avoid implicit conversions, making these strategies quite verbose. 

If this were a new project, I could just use NonEmptyArray instead of Array anywhere that it makes sense, which I imagine is in most places. But doing that conversion now would be too painful.

**Comment by BenLeggiero** [comment]
Your approach is basically what I would do. If only `Collection` required an initializer to transform its own subsequence into itself, this could be a convenience initializer:

```swift
import NonEmpty



public extension NonEmpty {
    init?(_ collection: C) {
        guard let first = collection.first else {
            return nil
        }
        
        self.init(first, C.init(collection.dropFirst()))
    }
}
```

**Comment by phlippieb** [comment]
Ok, thanks for your input. This is how I am using it in my project for now. With Swift in constant evolution, I'm hoping that some new way emerges to make this more convenient. But this answers my question for now, so I'll close the issue.
