### ISSUE TITLE
build fails using release config

### ISSUE THREAD

**Issue by tcldr** [pointfreeco/swift-nonempty#30]
If building using the release config on the master branch:

    swift build -c release

The build fails with a bunch of errors relating to Collection protocol conformance. Seems bizarre as the debug build works fine, so not sure if its a linker bug similar to SR-11564.

**Comment by stephencelis** [comment]
This is fixed on the main branch.

**Comment by tcldr** [comment]
@stephencelis Amazing! And thanks for providing a great library, Stephen!
