### ISSUE TITLE
Any plans on releasing a new version?

### ISSUE THREAD

**Issue by Noobish1** [pointfreeco/swift-nonempty#32]
Hi there, any plans on releasing a new version? One hasn't been released since https://github.com/pointfreeco/swift-nonempty/pull/26 was merged.

**Comment by maximkrouk** [comment]
Btw `0.2.2` seems unavailable for `swift-tools-version 5.3`, I think `0.2.3` should be released at least to support SwiftPM 5.3

**Comment by stephencelis** [comment]
We just released [0.3.0](https://github.com/pointfreeco/swift-nonempty/releases/tag/0.3.0)! There've been a lot of changes, so please file any issues you come across!
