### ISSUE TITLE
Don’t conform to StringProtocol

### ISSUE THREAD

**Issue by karwa** [pointfreeco/swift-nonempty#39]
> Do not declare new conformances to StringProtocol. Only the String and Substring types in the standard library are valid conforming types.

https://developer.apple.com/documentation/swift/stringprotocol

**Comment by karwa** [comment]
The conformance is here: https://github.com/pointfreeco/swift-nonempty/blob/4b9a77696c3135d121c1ba6c82a60a946bb6b603/Sources/NonEmpty/NonEmpty%2BString.swift#L63

**Comment by stephencelis** [comment]
Thanks! We should probably document that we believe it's OK to have this conformance, as the warning you refer to appears to be obsolete: https://forums.swift.org/t/stringprotocol-do-not-declare-new-conformances/6672/3

If you have any information to the contrary that compels us to remove the conformance, we're also totally open to it! We just haven't encountered one :smile:

**Comment by stephencelis** [comment]
Ended up removing this conformance. We still don't think it's necessarily a bad idea to conform, but we encountered a blocking compiler segfault while fixing another bug 😥
