### ISSUE TITLE
`ExpressibleByArrayLiteral` and `ExpressibleByDictionaryLiteral` conformances

### ISSUE THREAD

**Issue by fwcd** [pointfreeco/swift-nonempty#48]
It would be _very_ convenient to have these conformances, since non-empty collections could be initialized as naturally as the built-in collection types:

```swift
let x: NonEmpty<[Int]> = [1, 2, 3]
let y: NonEmpty<[Int: String]> = [1: "abc", 2: "def"]
```

However, since `ExpressibleByArrayLiteral` and `ExpressibleByDictionaryLiteral` don't allow their initializers to fail, we would have to crash at runtime, which might not be desirable given the description of the library as a compile-time guarantee:

```swift
init(arrayLiteral: Element...) {
  guard !arrayLiteral.isEmpty else { fatalError("Non-empty array literal!") }
  self.init(rawValue: arrayLiteral)!
}
```

or

```swift
init(arrayLiteral: Element...) {
  assert(!arrayLiteral.isEmpty, "Non-empty array literal!")
  self.init(rawValue: arrayLiteral)!
}
```

Thoughts?

**Comment by stephencelis** [comment]
@fwcd This sounds totally reasonable to us! Want to draft a PR implementing the functionality?

**Comment by fwcd** [comment]
Sure!
