### ISSUE TITLE
Sendable 

### ISSUE THREAD

**Issue by adriansergheev** [pointfreeco/swift-nonempty#56]
If the elements in the collection are Sendable, NonEmpty variant of it should be too

**Comment by mbrandonw** [comment]
Hi @adriansergheev, that's a good suggestion! Would you want to open a PR to add that? If not we can take care of it.

**Comment by adriansergheev** [comment]
it's a oneliner looks like!
https://github.com/pointfreeco/swift-nonempty/pull/57

**Comment by adriansergheev** [comment]
oh, should have checked opened pr's first...
looks like 
https://github.com/pointfreeco/swift-nonempty/pull/52 fixes it already.

**Comment by mbrandonw** [comment]
Oh oops, thanks for bringing that to our attention. We somehow lost track of it. We will look into it soon.
